rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
before_install:
  - gem install bundler
  - bundle --version
install:
  - bundle install
before_script:
  - bundle exec appraisal install
script:
  - bundle exec appraisal rake test
